package(default_visibility=["//visibility:public"])

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

kt_android_library(
    name = "doesthiswork",
    srcs = ["Item.java"],
    idl_srcs = ["ItemReceiver.aidl"],
    idl_parcelables = ["Item.aidl"],
)

#android_library(
#    name = "doesthiswork",
#    srcs = ["Item.java"],
#    idl_srcs = ["ItemReceiver.aidl"],
#    idl_parcelables = ["Item.aidl"],
#)

